version: "3.8"

services:
#  postgres:
#    image: postgres:13.3
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    container_name: db

  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_DATABASE=journal'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=123456'
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "8081:8081"
    container_name: app
    depends_on:
      - mysql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
volumes:
  postgres-data:
