version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - it-cube-network
    ports:
      - "3307:3307"


  backend:
    build: .
    ports:
      - "8081:8081"
    container_name: app
    networks:
      - it-cube-network
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  it-cube-network: