services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    container_name: db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: app
    depends_on:
      - postgres
