spring:
  datasource:
    url: jdbc:postgresql://db:5432/journal
    username: admin
    password: C4$+zN;K*Gh`agj=HJ7[(m
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  freemarker:
    expose-request-attributes: true
server:
  port: 8081