spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://db:3307/journal
    username: admin
    password: 12345
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    expose-request-attributes: true