spring:
  datasource:
    url: jdbc:mysql://localhost:3308/journal
    username: user
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update

  freemarker:
    expose-request-attributes: true
server:
  port: 8081