spring:
  application:
    name: itcubeservice

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_CLIENT_SECRET}
            client-name: ${KC_CLIENT_NAME}
            authorization-grant-type: authorization_code
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: ${KC_URL}/realms/itcubekld

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}

keycloak:
  url: ${KC_URL}
  realm: ${KC_REALM}
  client-id: ${KC_CLIENT_ID}
  client-secret: ${KC_CLIENT_SECRET}

external:
  keycloak:
    token-endpoint: "/realms/${KC_REALM}/protocol/openid-connect/token"
    revoke-endpoint: "/realms/${KC_REALM}/protocol/openid-connect/revoke"
    introspect-endpoint: "/realms/${KC_REALM}/protocol/openid-connect/token/introspect"
    admin:
      users-by-role-endpoint: "/admin/realms/${KC_REALM}/roles/{roleName}/users"
      user-by-id-endpoint: "/admin/realms/${KC_REALM}/users/{id}"
      user-role-mappings-endpoint: "/admin/realms/${KC_REALM}/users/{id}/role-mappings/realm/composite"

server:
  port: ${SERVER_PORT}